#!/bin/bash

# extract averaged betas from pooled ROIs


ROIs="VTA NAcc VmPFC"
subjects="sub-FG01 sub-FG02 sub-FG03 sub-FG04 sub-FG05 sub-FG06 sub-FG07 sub-FG09 sub-FG10 sub-FG11 sub-FG12 sub-FG14 sub-FG16 sub-FG17 sub-FG20 sub-FG22 sub-FG23 sub-FG25 sub-FG28R sub-FG29R sub-FG30R sub-FG31R sub-FG32R sub-FG33R sub-RG26 sub-RG27 sub-RG30 sub-RG31 sub-RG34 sub-RG37 sub-RG38 sub-RG41 sub-RG44 sub-RG47 sub-RG48 sub-RG49 sub-RG50 sub-RG51 sub-RG55R sub-RG56R sub-RG58R sub-RG59R sub-RG61R sub-RG62R sub-RG63R sub-RG64R"
task=Extinction

echo "SUBJ_ID,ROI,CSAV_CSM,CSM_CSAV,CSAV,CSM"
for subj in $subjects; do
  prefix="derivatives/afni/$subj/${task}"
  result_ROI_prefix="derivatives/afni/$subj/${task}/FL_results_ROI_pooled/"
  for roi in $ROIs; do
     roi_file="${result_ROI_prefix}/averaged_betas_from_${roi}.1D"
     awk -v SUBJ_ID=${subj#sub-} -v ROI=$roi '{ if(NR%4 == 1) { printf SUBJ_ID","ROI } printf ",%s",$1; if(NR%4==0) printf RS }' $roi_file
  done
done
