#!/bin/bash

dirA=derivatives/afni
dirP=derivatives/fmriprep
results_dir=$dirA/SL/AN-AVO
[ ! -d $results_dir ] && mkdir -p $results_dir

mask=$results_dir/mask_union_task-Avoidance.nii.gz
if [ ! -e $mask ]; then
   #intermediate_tmp=$(mktemp -u --suffix=.nii)
   #input=$dirP/sub-FG01/func/sub-FG01_task-Avoidance_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
   #input=derivatives/afni/sub-FG01/Avoidance/FL_results_WB_pooled/betas_REML+tlrc
   3dmask_tool -input $dirP/sub-*/func/sub-*_task-Avoidance_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz -prefix $mask -union
   #3dresample -master $input -prefix $mask -inset $intermediate_tmp -rmode NN
   #rm $intermediate_tmp
fi

#mask=derivatives/afni/SL/mean_gm_mask_resample.nii.gz

# factor A: FG (1) RG (2)
# factor B: AN (1) OM (2)
# factor C: csm (1) csav (2) csunav (3)

3dANOVA3 -type 1 \
  -alevels 2 \
  -blevels 2 \
  -clevels 3 \
  -fabc $results_dir/f_stat_full \
  -mask $mask \
  -dset 1   2	2	derivatives/afni/sub-FG01/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG01/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG01/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG01/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG01/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG02/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG02/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG02/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG02/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG02/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG03/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG03/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG03/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG03/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG03/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG04/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG04/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG04/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG04/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG04/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG05/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG05/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG05/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG05/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG05/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG06/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG06/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG06/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG06/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG06/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG07/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG07/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG07/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG07/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG07/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG09/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG09/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG09/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG09/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG09/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG10/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG10/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG10/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG10/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG10/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG11/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG11/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG11/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG11/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG11/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG12/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG12/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG12/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG12/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG12/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG14/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG14/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG14/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG14/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG14/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG15/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG15/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG15/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG15/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG15/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG16/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG16/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG16/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG16/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG16/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG17/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG17/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG17/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG17/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG17/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG20/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG20/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG20/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG20/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG20/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG22/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG22/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG22/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG22/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG22/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG23/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG23/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG23/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG23/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG23/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG25/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG25/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG25/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG25/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG25/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG28R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG28R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG28R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG28R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG28R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG29R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG29R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG29R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG29R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG29R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG30R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG30R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG30R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG30R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG30R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG31R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG31R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG31R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG31R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG31R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG32R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG32R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG32R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG32R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG32R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 1   2	2	derivatives/afni/sub-FG33R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 1   2	1	derivatives/afni/sub-FG33R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 1   1	1	derivatives/afni/sub-FG33R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 1   1	2	derivatives/afni/sub-FG33R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 1   1	3	derivatives/afni/sub-FG33R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG26/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG26/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG26/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG26/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG26/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG27/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG27/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG27/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG27/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG27/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG30/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG30/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG30/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG30/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG30/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG31/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG31/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG31/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG31/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG31/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG32/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG32/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG32/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG32/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG32/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG33/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG33/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG33/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG33/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG33/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG34/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG34/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG34/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG34/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG34/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG35/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG35/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG35/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG35/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG35/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG37/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG37/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG37/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG37/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG37/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG38/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG38/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG38/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG38/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG38/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG41/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG41/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG41/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG41/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG41/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG44/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG44/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG44/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG44/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG44/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG47/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG47/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG47/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG47/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG47/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG48/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG48/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG48/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG48/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG48/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG49/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG49/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG49/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG49/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG49/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG50/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG50/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG50/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG50/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG50/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG51/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG51/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG51/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG51/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG51/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG55R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG55R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG55R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG55R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG55R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG56R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG56R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG56R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG56R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG56R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG58R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG58R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG58R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG58R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG58R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG59R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG59R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG59R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG59R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG59R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG61R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG61R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG61R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG61R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG61R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG62R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG62R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG62R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG62R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG62R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG63R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG63R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG63R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG63R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG63R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]' \
  -dset 2   2	2	derivatives/afni/sub-RG64R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csav#0_Coef]' \
  -dset 2   2	1	derivatives/afni/sub-RG64R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[csm#0_Coef]' \
  -dset 2   1	1	derivatives/afni/sub-RG64R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csm#0_Coef]' \
  -dset 2   1	2	derivatives/afni/sub-RG64R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csav#0_Coef]' \
  -dset 2   1	3	derivatives/afni/sub-RG64R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc'[onset_csunav#0_Coef]'
