#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.1 (May 11, 2020)
# creation date: Fri Feb 11 10:02:02 2022

# ---------------------- set process variables ----------------------

set dirA = /home/thaber/FASTING_MRI_BIDS/derivatives/afni
set dirP = /home/thaber/FASTING_MRI_BIDS/derivatives/fmriprep

# specify and possibly create results directory
set results_dir = $dirA/SL
if ( ! -d $results_dir ) mkdir $results_dir

set mask_dset = $results_dir/mask_union_task-Avoidance.nii.gz
if ( ! -e $mask_dset ) 3dmask_tool -input $dirP/sub-*/func/sub-*_task-Avoidance_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz -prefix $mask_dset -union


# ------------------------- process the data -------------------------

3dMEMA -prefix $results_dir/SL_pooled_WB_t_test_csav_vs_csm_AVO.mema                       \
          -groups FG RG \
          -mask $mask_dset                                                  \
          -set FG                                                      \
             01                                                             \
          "$dirA/sub-FG01/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG01/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             02                                                             \
          "$dirA/sub-FG02/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG02/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             03                                                             \
          "$dirA/sub-FG03/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG03/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             04                                                             \
          "$dirA/sub-FG04/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG04/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             05                                                             \
          "$dirA/sub-FG05/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG05/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             06                                                             \
          "$dirA/sub-FG06/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG06/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             07                                                             \
          "$dirA/sub-FG07/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG07/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             09                                                             \
          "$dirA/sub-FG09/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG09/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             10                                                             \
          "$dirA/sub-FG10/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG10/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             11                                                             \
          "$dirA/sub-FG11/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG11/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             12                                                             \
          "$dirA/sub-FG12/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG12/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             14                                                             \
          "$dirA/sub-FG14/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG14/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             15                                                             \
          "$dirA/sub-FG15/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG15/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             16                                                             \
          "$dirA/sub-FG16/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG16/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             17                                                             \
          "$dirA/sub-FG17/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG17/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             20                                                             \
          "$dirA/sub-FG20/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG20/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             22                                                             \
          "$dirA/sub-FG22/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG22/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             23                                                             \
          "$dirA/sub-FG23/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG23/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             25                                                             \
          "$dirA/sub-FG25/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG25/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             28R                                                            \
          "$dirA/sub-FG28R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG28R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             29R                                                            \
          "$dirA/sub-FG29R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG29R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             30R                                                            \
          "$dirA/sub-FG30R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG30R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             31R                                                            \
          "$dirA/sub-FG31R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG31R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             32R                                                            \
          "$dirA/sub-FG32R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG32R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             33R                                                            \
          "$dirA/sub-FG33R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-FG33R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
          -set RG   \
             26                                                             \
          "$dirA/sub-RG26/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG26/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             27                                                             \
          "$dirA/sub-RG27/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG27/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             30                                                             \
          "$dirA/sub-RG30/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG30/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             31                                                             \
          "$dirA/sub-RG31/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG31/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             32                                                             \
          "$dirA/sub-RG32/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG32/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             33                                                             \
          "$dirA/sub-RG33/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG33/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             34                                                             \
          "$dirA/sub-RG34/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG34/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             35                                                             \
          "$dirA/sub-RG35/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG35/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             37                                                             \
          "$dirA/sub-RG37/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG37/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             38                                                             \
          "$dirA/sub-RG38/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG38/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             41                                                             \
          "$dirA/sub-RG41/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG41/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             44                                                             \
          "$dirA/sub-RG44/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG44/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             47                                                             \
          "$dirA/sub-RG47/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG47/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             48                                                             \
          "$dirA/sub-RG48/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG48/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             49                                                             \
          "$dirA/sub-RG49/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG49/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             50                                                             \
          "$dirA/sub-RG50/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG50/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             51                                                             \
          "$dirA/sub-RG51/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG51/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             55R                                                            \
          "$dirA/sub-RG55R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG55R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             56R                                                            \
          "$dirA/sub-RG56R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG56R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             58R                                                            \
          "$dirA/sub-RG58R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG58R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             59R                                                            \
          "$dirA/sub-RG59R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG59R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             61R                                                            \
          "$dirA/sub-RG61R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG61R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             62R                                                            \
          "$dirA/sub-RG62R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG62R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             63R                                                            \
          "$dirA/sub-RG63R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG63R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]" \
             64R                                                            \
          "$dirA/sub-RG64R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[17]" \
          "$dirA/sub-RG64R/Avoidance/FL_results_WB_pooled_hp/betas_REML+tlrc[18]"

