#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.1 (May 11, 2020)
# creation date: Fri Feb 11 10:02:02 2022

# ---------------------- set process variables ----------------------

set dirA = derivatives/afni
set dirP = derivatives/fmriprep

# specify and possibly create results directory
set results_dir = $dirA/SL/AVO
if ( ! -d $results_dir ) mkdir $results_dir

set mask_dset = $dirA/SL/mean_gm_mask_resample.nii.gz
if ( ! -e $mask_dset ) 3dresample -master $dirP/sub-FG01/func/sub-FG01_task-Avoidance_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz -prefix $mask_dset -inset $dirA/SL/mean_gm_mask.nii.gz -rmode NN

if ( -e $results_dir/SL_pooled_WB_3dttest_csm_vs_csav_AVO_diff_groups+tlrc.BRIK ) rm $results_dir/SL_pooled_WB_3dttest_csm_vs_csav_AVO_diff_groups+tlrc.*
# ------------------------- process the data -------------------------

3dttest++ -Clustsim -prefix $results_dir/SL_pooled_WB_3dttest_csm_vs_csav_AVO_diff_groups -AminusB                         \
          -mask $mask_dset                                                  \
          -setA FG                                                       \
             01                                                             \
          "$dirA/sub-FG01/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             02                                                             \
          "$dirA/sub-FG02/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             03                                                             \
          "$dirA/sub-FG03/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             04                                                             \
          "$dirA/sub-FG04/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             05                                                             \
          "$dirA/sub-FG05/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             06                                                             \
          "$dirA/sub-FG06/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             07                                                             \
          "$dirA/sub-FG07/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             09                                                             \
          "$dirA/sub-FG09/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             10                                                             \
          "$dirA/sub-FG10/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             11                                                             \
          "$dirA/sub-FG11/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             12                                                             \
          "$dirA/sub-FG12/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             14                                                             \
          "$dirA/sub-FG14/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             15                                                             \
          "$dirA/sub-FG15/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             16                                                             \
          "$dirA/sub-FG16/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             17                                                             \
          "$dirA/sub-FG17/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             20                                                             \
          "$dirA/sub-FG20/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             22                                                             \
          "$dirA/sub-FG22/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             23                                                             \
          "$dirA/sub-FG23/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             25                                                             \
          "$dirA/sub-FG25/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             28R                                                            \
          "$dirA/sub-FG28R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             29R                                                            \
          "$dirA/sub-FG29R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             30R                                                            \
          "$dirA/sub-FG30R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             31R                                                            \
          "$dirA/sub-FG31R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             32R                                                            \
          "$dirA/sub-FG32R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             33R                                                            \
          "$dirA/sub-FG33R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
          -setB RG                                                       \
             26                                                             \
          "$dirA/sub-RG26/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             27                                                             \
          "$dirA/sub-RG27/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             30                                                             \
          "$dirA/sub-RG30/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             31                                                             \
          "$dirA/sub-RG31/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             32                                                             \
          "$dirA/sub-RG32/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             33                                                             \
          "$dirA/sub-RG33/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             34                                                             \
          "$dirA/sub-RG34/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             35                                                             \
          "$dirA/sub-RG35/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             37                                                             \
          "$dirA/sub-RG37/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             38                                                             \
          "$dirA/sub-RG38/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             41                                                             \
          "$dirA/sub-RG41/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             44                                                             \
          "$dirA/sub-RG44/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             47                                                             \
          "$dirA/sub-RG47/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             48                                                             \
          "$dirA/sub-RG48/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             49                                                             \
          "$dirA/sub-RG49/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             50                                                             \
          "$dirA/sub-RG50/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             51                                                             \
          "$dirA/sub-RG51/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"  \
             55R                                                            \
          "$dirA/sub-RG55R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             56R                                                            \
          "$dirA/sub-RG56R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             58R                                                            \
          "$dirA/sub-RG58R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             59R                                                            \
          "$dirA/sub-RG59R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             61R                                                            \
          "$dirA/sub-RG61R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             62R                                                            \
          "$dirA/sub-RG62R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             63R                                                            \
          "$dirA/sub-RG63R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]" \
             64R                                                            \
          "$dirA/sub-RG64R/Avoidance/FL_results_WB_pooled/betas_REML+tlrc[21]"

