#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.1 (May 11, 2020)
# creation date: Sun Feb  6 23:30:45 2022

# ---------------------- set process variables ----------------------

set dirA = /home/thaber/FASTING_MRI_BIDS/derivatives/afni
set dirP = /home/thaber/FASTING_MRI_BIDS/derivatives/fmriprep

# specify and possibly create results directory
set results_dir = $dirA/SL
if ( ! -d $results_dir ) mkdir $results_dir

set mask_dset = $results_dir/mask_union_task-Extinction.nii.gz
if ( ! -e $mask_dset ) 3dmask_tool -input $dirP/sub-*/func/sub-*_task-Extinction_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz -prefix $mask_dset -union

# ------------------------- process the data -------------------------

3dttest++ -prefix $results_dir/SL_pooled_WB_t_test_csav_csm_EXT -AminusB         \
          -mask $mask_dset                                                   \
          -setA FG                                                          \
             01                                                              \
          "$dirA/sub-FG01/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             02                                                              \
          "$dirA/sub-FG02/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             03                                                              \
          "$dirA/sub-FG03/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             04                                                              \
          "$dirA/sub-FG04/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             05                                                              \
          "$dirA/sub-FG05/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             06                                                              \
          "$dirA/sub-FG06/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             07                                                              \
          "$dirA/sub-FG07/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             09                                                              \
          "$dirA/sub-FG09/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             10                                                              \
          "$dirA/sub-FG10/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             11                                                              \
          "$dirA/sub-FG11/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             12                                                              \
          "$dirA/sub-FG12/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             14                                                              \
          "$dirA/sub-FG14/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             16                                                              \
          "$dirA/sub-FG16/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             17                                                              \
          "$dirA/sub-FG17/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             20                                                              \
          "$dirA/sub-FG20/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             22                                                              \
          "$dirA/sub-FG22/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             23                                                              \
          "$dirA/sub-FG23/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             25                                                              \
          "$dirA/sub-FG25/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             28R                                                             \
          "$dirA/sub-FG28R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             29R                                                             \
          "$dirA/sub-FG29R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             30R                                                             \
          "$dirA/sub-FG30R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             31R                                                             \
          "$dirA/sub-FG31R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             32R                                                             \
          "$dirA/sub-FG32R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             33R                                                             \
          "$dirA/sub-FG33R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
          -setB RG                                                           \
             26                                                              \
          "$dirA/sub-RG26/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             27                                                              \
          "$dirA/sub-RG27/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             30                                                              \
          "$dirA/sub-RG30/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             31                                                              \
          "$dirA/sub-RG31/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             34                                                              \
          "$dirA/sub-RG34/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             37                                                              \
          "$dirA/sub-RG37/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             38                                                              \
          "$dirA/sub-RG38/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             41                                                              \
          "$dirA/sub-RG41/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             44                                                              \
          "$dirA/sub-RG44/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             47                                                              \
          "$dirA/sub-RG47/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             48                                                              \
          "$dirA/sub-RG48/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             49                                                              \
          "$dirA/sub-RG49/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             50                                                              \
          "$dirA/sub-RG50/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             51                                                              \
          "$dirA/sub-RG51/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"  \
             55R                                                             \
          "$dirA/sub-RG55R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             56R                                                             \
          "$dirA/sub-RG56R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             58R                                                             \
          "$dirA/sub-RG58R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             59R                                                             \
          "$dirA/sub-RG59R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             61R                                                             \
          "$dirA/sub-RG61R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             62R                                                             \
          "$dirA/sub-RG62R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             63R                                                             \
          "$dirA/sub-RG63R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]" \
             64R                                                             \
          "$dirA/sub-RG64R/Extinction/FL_results_WB_pooled/statsWB+tlrc[10]"

