#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.1 (May 11, 2020)
# creation date: Fri Feb 11 10:02:02 2022

# ---------------------- set process variables ----------------------

set dirA = derivatives/afni
set dirP = derivatives/fmriprep

# specify and possibly create results directory
set results_dir = $dirA/SL/EXT
if ( ! -d $results_dir ) mkdir $results_dir

set mask_dset = $dirA/mergedROIs_resam.nii

if ( -e $results_dir/SL_pooled_WB_3dttest_csav_AND_csm_EXT_mergedROIs_differences_groups_general_OMISSION+tlrc.BRIK ) rm $results_dir/SL_pooled_WB_3dttest_csav_AND_csm_EXT_mergedROIs_differences_groups_general_OMISSION+tlrc.*
# ------------------------- process the data -------------------------

3dttest++ -Clustsim -prefix $results_dir/SL_pooled_WB_3dttest_csav_AND_csm_EXT_mergedROIs_differences_groups_general_OMISSION -AminusB                        \
          -mask $mask_dset\
          -setA csavANDcsm_FG                                                       \
             FG01                                                             \
          "$dirA/sub-FG01/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG02                                                             \
          "$dirA/sub-FG02/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG03                                                             \
          "$dirA/sub-FG03/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG04                                                             \
          "$dirA/sub-FG04/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG05                                                             \
          "$dirA/sub-FG05/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG06                                                             \
          "$dirA/sub-FG06/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG07                                                             \
          "$dirA/sub-FG07/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG09                                                             \
          "$dirA/sub-FG09/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG10                                                             \
          "$dirA/sub-FG10/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG11                                                             \
          "$dirA/sub-FG11/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG12                                                             \
          "$dirA/sub-FG12/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG14                                                             \
          "$dirA/sub-FG14/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG16                                                             \
          "$dirA/sub-FG16/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG17                                                             \
          "$dirA/sub-FG17/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG20                                                             \
          "$dirA/sub-FG20/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG22                                                             \
          "$dirA/sub-FG22/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG23                                                             \
          "$dirA/sub-FG23/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG25                                                             \
          "$dirA/sub-FG25/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             FG28R                                                            \
          "$dirA/sub-FG28R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             FG29R                                                            \
          "$dirA/sub-FG29R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             FG30R                                                            \
          "$dirA/sub-FG30R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             FG31R                                                            \
          "$dirA/sub-FG31R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             FG32R                                                            \
          "$dirA/sub-FG32R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             FG33R                                                            \
          "$dirA/sub-FG33R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
          -setB csavANDcsm_RG                                                       \
             RG26                                                             \
          "$dirA/sub-RG26/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             RG27                                                             \
          "$dirA/sub-RG27/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG30                                                             \
          "$dirA/sub-RG30/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG31                                                             \
          "$dirA/sub-RG31/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG34                                                             \
          "$dirA/sub-RG34/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG37                                                             \
          "$dirA/sub-RG37/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG38                                                             \
          "$dirA/sub-RG38/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG41                                                             \
          "$dirA/sub-RG41/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG44                                                             \
          "$dirA/sub-RG44/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG47                                                             \
          "$dirA/sub-RG47/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG48                                                             \
          "$dirA/sub-RG48/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG49                                                             \
          "$dirA/sub-RG49/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG50                                                             \
          "$dirA/sub-RG50/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG51                                                             \
          "$dirA/sub-RG51/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]"  \
             RG55R                                                            \
          "$dirA/sub-RG55R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             56R                                                            \
          "$dirA/sub-RG56R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             58R                                                            \
          "$dirA/sub-RG58R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             59R                                                            \
          "$dirA/sub-RG59R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             61R                                                            \
          "$dirA/sub-RG61R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             62R                                                            \
          "$dirA/sub-RG62R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             63R                                                            \
          "$dirA/sub-RG63R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" \
             64R                                                            \
          "$dirA/sub-RG64R/Extinction/FL_results_VW_mergedROIs/betas_REML+tlrc[13]" 
     
