#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.1 (May 11, 2020)
# creation date: Fri Feb 11 10:02:02 2022

# ---------------------- set process variables ----------------------

set dirA = derivatives/afni
set dirP = FASTING_MRI_BIDS/derivatives/fmriprep

# specify and possibly create results directory
set results_dir = $dirA/SL/EXT
if ( ! -d $results_dir ) mkdir $results_dir

#set mask_dset = $dirA/SL/mean_gm_mask_resample.nii.gz
#if ( ! -e $mask_dset ) 3dresample -master $dirP/sub-FG01/func/sub-FG01_task-Extinction_space-MNI152NLin20011cAsym_desc-brain_mask.nii.gz -prefix $mask_dset -inset $dirA/SL/mean_gm_mask.nii.gz -rmode NN
set mask_dset = $results_dir/mask_union_task-Extinction.nii.gz
if ( ! -e $mask_dset ) 3dmask_tool -input $dirP/sub-*/func/sub-*_task-Extinction_space-MNI152NLin20011cAsym_desc-brain_mask.nii.gz -prefix $mask_dset -union


if ( -e $results_dir/SL_pooled_WB_3dttest_csav_vs_csm_EXT_across_groups_late_ANTICIPATION+tlrc.BRIK ) rm $results_dir/SL_pooled_WB_3dttest_csav_vs_csm_EXT_across_groups_late_ANTICIPATION.* 
# ------------------------- process the data -------------------------

3dttest++ -Clustsim -prefix $results_dir/SL_pooled_WB_3dttest_csav_vs_csm_EXT_across_groups_late_ANTICIPATION  -AminusB                         \
          -mask $mask_dset \
          -setA latecsav                                                       \
             01                                                             \
          "$dirA/sub-FG01/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             02                                                             \
          "$dirA/sub-FG02/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             03                                                             \
          "$dirA/sub-FG03/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             04                                                             \
          "$dirA/sub-FG04/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             05                                                             \
          "$dirA/sub-FG05/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             06                                                             \
          "$dirA/sub-FG06/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             07                                                             \
          "$dirA/sub-FG07/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             09                                                             \
          "$dirA/sub-FG09/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             10                                                             \
          "$dirA/sub-FG10/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             11                                                             \
          "$dirA/sub-FG11/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             12                                                             \
          "$dirA/sub-FG12/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             14                                                             \
          "$dirA/sub-FG14/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             16                                                             \
          "$dirA/sub-FG16/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             17                                                             \
          "$dirA/sub-FG17/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             20                                                             \
          "$dirA/sub-FG20/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             22                                                             \
          "$dirA/sub-FG22/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             23                                                             \
          "$dirA/sub-FG23/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             25                                                             \
          "$dirA/sub-FG25/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             28R                                                            \
          "$dirA/sub-FG28R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             29R                                                            \
          "$dirA/sub-FG29R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             30R                                                            \
          "$dirA/sub-FG30R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             31R                                                            \
          "$dirA/sub-FG31R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             32R                                                            \
          "$dirA/sub-FG32R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             33R                                                            \
          "$dirA/sub-FG33R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             26                                                             \
          "$dirA/sub-RG26/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             27                                                             \
          "$dirA/sub-RG27/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             30                                                             \
          "$dirA/sub-RG30/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             31                                                             \
          "$dirA/sub-RG31/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             34                                                             \
          "$dirA/sub-RG34/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             37                                                             \
          "$dirA/sub-RG37/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             38                                                             \
          "$dirA/sub-RG38/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             41                                                             \
          "$dirA/sub-RG41/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             44                                                             \
          "$dirA/sub-RG44/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             47                                                             \
          "$dirA/sub-RG47/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             48                                                             \
          "$dirA/sub-RG48/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             49                                                             \
          "$dirA/sub-RG49/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             50                                                             \
          "$dirA/sub-RG50/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             51                                                             \
          "$dirA/sub-RG51/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]"  \
             55R                                                            \
          "$dirA/sub-RG55R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             56R                                                            \
          "$dirA/sub-RG56R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             58R                                                            \
          "$dirA/sub-RG58R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             59R                                                            \
          "$dirA/sub-RG59R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             61R                                                            \
          "$dirA/sub-RG61R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             62R                                                            \
          "$dirA/sub-RG62R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             63R                                                            \
          "$dirA/sub-RG63R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
             64R                                                            \
          "$dirA/sub-RG64R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[17]" \
          -setB latecsm                                                       \
             01                                                             \
          "$dirA/sub-FG01/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             02                                                             \
          "$dirA/sub-FG02/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             03                                                             \
          "$dirA/sub-FG03/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             04                                                             \
          "$dirA/sub-FG04/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             05                                                             \
          "$dirA/sub-FG05/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             06                                                             \
          "$dirA/sub-FG06/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             07                                                             \
          "$dirA/sub-FG07/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             09                                                             \
          "$dirA/sub-FG09/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             10                                                             \
          "$dirA/sub-FG10/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             11                                                             \
          "$dirA/sub-FG11/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             12                                                             \
          "$dirA/sub-FG12/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             14                                                             \
          "$dirA/sub-FG14/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             16                                                             \
          "$dirA/sub-FG16/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             17                                                             \
          "$dirA/sub-FG17/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             20                                                             \
          "$dirA/sub-FG20/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             22                                                             \
          "$dirA/sub-FG22/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             23                                                             \
          "$dirA/sub-FG23/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             25                                                             \
          "$dirA/sub-FG25/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             28R                                                            \
          "$dirA/sub-FG28R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             29R                                                            \
          "$dirA/sub-FG29R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             30R                                                            \
          "$dirA/sub-FG30R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             31R                                                            \
          "$dirA/sub-FG31R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             32R                                                            \
          "$dirA/sub-FG32R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             26                                                             \
          "$dirA/sub-RG26/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             27                                                             \
          "$dirA/sub-RG27/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             30                                                             \
          "$dirA/sub-RG30/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             31                                                             \
          "$dirA/sub-RG31/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             34                                                             \
          "$dirA/sub-RG34/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             37                                                             \
          "$dirA/sub-RG37/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             38                                                             \
          "$dirA/sub-RG38/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             41                                                             \
          "$dirA/sub-RG41/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             44                                                             \
          "$dirA/sub-RG44/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             47                                                             \
          "$dirA/sub-RG47/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             48                                                             \
          "$dirA/sub-RG48/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             49                                                             \
          "$dirA/sub-RG49/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             50                                                             \
          "$dirA/sub-RG50/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             51                                                             \
          "$dirA/sub-RG51/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]"  \
             55R                                                            \
          "$dirA/sub-RG55R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             56R                                                            \
          "$dirA/sub-RG56R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             58R                                                            \
          "$dirA/sub-RG58R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             59R                                                            \
          "$dirA/sub-RG59R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             61R                                                            \
          "$dirA/sub-RG61R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             62R                                                            \
          "$dirA/sub-RG62R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             63R                                                            \
          "$dirA/sub-RG63R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" \
             64R                                                            \
          "$dirA/sub-RG64R/Extinction/FL_results_WB_pooled_early_late/betas_REML+tlrc[15]" 
