#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.1 (May 11, 2020)
# creation date: Thu Apr 14 07:10:10 2022

# ---------------------- set process variables ----------------------

set dirA = /home/thaber/FASTING_MRI_BIDS/derivatives/afni
set dirP = /home/thaber/FASTING_MRI_BIDS/derivatives/fmriprep

# specify and possibly create results directory
set results_dir = $dirA/SL
if ( ! -d $results_dir ) mkdir $results_dir

set mask_dset = $results_dir/mean_gm_mask_resample.nii.gz

# ------------------------- process the data -------------------------

3dttest++ -prefix $results_dir/SL_WB_ttest_omissioncsav_vs_omissioncsm_across_groups \
          -mask $mask_dset \
          -setA FGandRG \
             01 \
          "$dirA/sub-FG01/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             02 \
          "$dirA/sub-FG02/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             03                                                                               \
          "$dirA/sub-FG03/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             04                                                                               \
          "$dirA/sub-FG04/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             05                                                                               \
          "$dirA/sub-FG05/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             06                                                                               \
          "$dirA/sub-FG06/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             07                                                                               \
          "$dirA/sub-FG07/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             09                                                                               \
          "$dirA/sub-FG09/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             10                                                                               \
          "$dirA/sub-FG10/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             11                                                                               \
          "$dirA/sub-FG11/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             12                                                                               \
          "$dirA/sub-FG12/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             14                                                                               \
          "$dirA/sub-FG14/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             16                                                                               \
          "$dirA/sub-FG16/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             17                                                                               \
          "$dirA/sub-FG17/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             20                                                                               \
          "$dirA/sub-FG20/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             22                                                                               \
          "$dirA/sub-FG22/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             23                                                                               \
          "$dirA/sub-FG23/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             25                                                                               \
          "$dirA/sub-FG25/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             28R                                                                              \
          "$dirA/sub-FG28R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             29R                                                                              \
          "$dirA/sub-FG29R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             30R                                                                              \
          "$dirA/sub-FG30R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             31R                                                                              \
          "$dirA/sub-FG31R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             32R                                                                               \
          "$dirA/sub-FG32R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             33R                                                                               \
          "$dirA/sub-FG33R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             26                                                                                \
          "$dirA/sub-RG26/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             27                                                                               \
          "$dirA/sub-RG27/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             30                                                                               \
          "$dirA/sub-RG30/Extinction/FL_results_WB_pooled/betas_REML+tlrc[15]"\
             31                                                                               \
          "$dirA/sub-RG31/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             34                                                                               \
          "$dirA/sub-RG34/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             37                                                                               \
          "$dirA/sub-RG37/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             38                                                                               \
          "$dirA/sub-RG38/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             41                                                                               \
          "$dirA/sub-RG41/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             44                                                                               \
          "$dirA/sub-RG44/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             47                                                                               \
          "$dirA/sub-RG47/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             48                                                                               \
          "$dirA/sub-RG48/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             49                                                                               \
          "$dirA/sub-RG49/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             50                                                                               \
          "$dirA/sub-RG50/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             51                                                                               \
          "$dirA/sub-RG51/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             55R                                                                              \
          "$dirA/sub-RG55R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             56R                                                                               \
          "$dirA/sub-RG56R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             58R                                                                               \
          "$dirA/sub-RG58R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             59R                                                                               \
          "$dirA/sub-RG59R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             61R                                                                               \
          "$dirA/sub-RG61R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             62R                                                                               \
          "$dirA/sub-RG62R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             63R                                                                               \
          "$dirA/sub-RG63R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"\
             64R                                                                              \
          "$dirA/sub-RG64R/Extinction/FL_results_WB_pooled/betas_REML+tlrc[11]"
