#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.1 (May 11, 2020)
# creation date: Thu Apr 14 07:10:10 2022

# ---------------------- set process variables ----------------------

set dirA = /home/thaber/FASTING_MRI_BIDS/derivatives/afni
set dirP = /home/thaber/FASTING_MRI_BIDS/derivatives/fmriprep

# specify and possibly create results directory
set results_dir = $dirA/SL
if ( ! -d $results_dir ) mkdir $results_dir

set mask_dset = $results_dir/mask_union_task-Extinction.nii.gz
if ( ! -e $mask_dset ) 3dmask_tool -input $dirP/sub-*/func/sub-*_task-Extinction_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz -prefix $mask_dset -union

# ------------------------- process the data -------------------------

3dttest++ -prefix $results_dir/SL_WB_ttest_csavnonM_csavM_EXT_FG \
          -mask $mask_dset \
          -setA FG \
             01 \
          "$dirA/sub-FG01/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             02 \
          "$dirA/sub-FG02/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             03                                                                               \
          "$dirA/sub-FG03/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             04                                                                               \
          "$dirA/sub-FG04/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             05                                                                               \
          "$dirA/sub-FG05/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[11]"\
             06                                                                               \
          "$dirA/sub-FG06/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             07                                                                               \
          "$dirA/sub-FG07/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             09                                                                               \
          "$dirA/sub-FG09/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             10                                                                               \
          "$dirA/sub-FG10/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             11                                                                               \
          "$dirA/sub-FG11/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             12                                                                               \
          "$dirA/sub-FG12/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             14                                                                               \
          "$dirA/sub-FG14/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             16                                                                               \
          "$dirA/sub-FG16/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             17                                                                               \
          "$dirA/sub-FG17/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             20                                                                               \
          "$dirA/sub-FG20/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             22                                                                               \
          "$dirA/sub-FG22/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             23                                                                               \
          "$dirA/sub-FG23/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             25                                                                               \
          "$dirA/sub-FG25/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             28R                                                                              \
          "$dirA/sub-FG28R/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             29R                                                                              \
          "$dirA/sub-FG29R/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             30R                                                                              \
          "$dirA/sub-FG30R/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             31R                                                                              \
          "$dirA/sub-FG31R/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             32R                                                                               \
          "$dirA/sub-FG32R/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"\
             33R                                                                               \
          "$dirA/sub-FG33R/Extinction/FL_results_WB_parametric_modulation/betas_REML+tlrc[15]"
